### ISSUE TITLE
Protocols & Data Preprocessing on MPI-INF-3DHP

### ISSUE THREAD

**Issue by GloryyrolG** [twehrbein/Probabilistic-Monocular-3D-Human-Pose-Estimation-with-Normalizing-Flows#7]
Hi @twehrbein , @marco-rudolph , @bastianwandt ,

It is good to see the method achieves a good generalization of **86.9** on MPI-INF-3DHP. It would be better if you could share some details on how to reproduce the result, \eg,
- if similar data preprocessing (-mean/std) as Human3.6M is adopted for 3DHP,
- if so, if mean and std used are re-computed on 3DHP,
- and if 3D output poses are PA-aligned (to remove scale and rotation) before computing errors.

Any help would be greatly appreciated.:)

Thanks & regards,

**Comment by GloryyrolG** [comment]
& if I were not wrong, it seems usually we use *original 2D* as input instead of *cropped 2D coordinates*, right?

https://github.com/twehrbein/Probabilistic-Monocular-3D-Human-Pose-Estimation-with-Normalizing-Flows/blob/ad2fdf21da1dfb689a5c2a531ebda6e23d95ccc0/data/data_h36m.py#L93

**Comment by twehrbein** [comment]
Hi @GloryyrolG !

We apply exactly the same data preprocessing for H36M and 3DHP. Note that we do not use statistics (i.e. mean and std) of the datasets, but simply center each pose to its mean and divide by its standard deviation. See code [here](https://github.com/twehrbein/Probabilistic-Monocular-3D-Human-Pose-Estimation-with-Normalizing-Flows/blob/main/utils/data_utils.py#L81).
The predicted poses are not PA-aligned when computing PCK.

> if I were not wrong, it seems usually we use original 2D as input instead of cropped 2D coordinates, right?

We use normalized 2D poses as input. Due to the normalization (see above), it does not matter if the 2D poses are in full or cropped image coordinates before normalization.
"p2d_hrnet_unnorm" is saved only for visualization purposes.
